Started logging messages at Sat Oct 22 10:50:13 2022
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 23 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 67
Info:            Created 
Info:        Working on 68
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 94
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 277
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 377
Info:            Created 
Info:        Working on 445
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 436
Info:            Created 
Info:        Working on 404
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 293
Info:            Created 
Info:        Working on 222
Info:            Created 
Info:        Working on 152
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 268
Info:            Created 
Info:        Working on 192
Info:            Created 
Info:        Working on 258
Info:            Created 
Info:        Working on 269
Info:            Created 
Info:        Working on 19
Info:            Created 
Info:        Working on 193
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 364
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 440
Info:            Created 
Info:        Working on 453
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Working on 427
Info:            Created 
Info:        Working on 326
Info:            Created 
Info:        Working on 325
Info:            Created 
Info:        Working on 415
Info:            Created 
Info:        Working on 393
Info:            Created 
Info:        Working on 346
Info:            Created 
Info:        Working on 46
Info:            Created 
Info:        Working on 72
Info:            Created 
Info:        Working on 111
Info:            Created 
Info:        Working on 169
Info:            Created 
Info:        Working on 234
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 411
Info:            Created 
Info:        Working on 421
Info:            Created 
Info:        Working on 281
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 408
Info:            Created 
Info:        Working on 281
Info:            Created 
Info:        Working on 160
Info:            Created 
Info:        Working on 229
Info:            Created 
Info:        Working on 107
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 340
Info:            Created 
Info:        Working on 226
Info:            Created 
Info:        Working on 365
Info:            Created 
Info:        Working on 267
Info:            Created 
Info:        Working on 304
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 2.41184e-05
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Oct 22 10:50:13 2022
